export const platformAdapter = {
  toFrontend: (raw) => ({
    pf_key: raw.pf_key ?? raw.pf_id, 
    pf_id: raw.pf_id,
    pf_name: raw.pf_name,
    pf_type: raw.pf_type,
    pf_squadron: raw.pf_squadron,
    pf_status: raw.pf_status,
    pf_co: raw.pf_co,
    pf_fuelcap: raw.pf_fuelcap,
    pf_watercap: raw.pf_watercap,
    pf_info: raw.pf_info,
  }),
  toBackend: (platform) => ({
    pf_id: platform.pf_id ?? platform.pf_key,
    pf_key: platform.pf_key,
    pf_name: platform.pf_name,
    pf_type: platform.pf_type,
    pf_squadron: platform.pf_squadron,
    pf_status: platform.pf_status,
    pf_co: platform.pf_co,
    pf_fuelcap: platform.pf_fuelcap,
    pf_watercap: platform.pf_watercap,
    pf_info: platform.pf_info,
  }),
};
